import * as S from '../../styles/GeneralTermsStyles/styles';
import { NextPage } from 'next';
import Head from 'next/head';
import { GeneralTermsComp } from '../../components/FC/GeneralTermsComp';
import logoFuturista from '../../assets/Icon-Vereda/logoFuturista.png';
import Image from 'next/image';

const GeneralTerms: NextPage = () => {
  return (
    <>
      <Head>
        <title>Termos Gerais | ConsultPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.View>
        <S.Container>
          <header>
            <Image
              className="image-header"
              alt="logoFuturistic"
              src={logoFuturista}
              width={70}
              height={70}
            />
            <h1>Ficha nutricional</h1>
          </header>

          <main>
            <GeneralTermsComp />
          </main>
        </S.Container>
      </S.View>
    </>
  );
};

export default GeneralTerms;
