import * as S from '../styles/homePageStyles/index';
import { NextPage } from 'next';
import Head from 'next/head';
import { NutritionalCont } from '../components/FC/NutritionalCont';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ficha de Saúde | ConsultPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container>
        <S.Header>
          <NutritionalCont />
        </S.Header>
      </S.Container>
    </>
  );
};

export default Home;
