import * as S from '../../styles/ShippingConfirmationStyles/styles';
import { NextPage } from 'next';
import Head from 'next/head';

const ShippingConfirmation: NextPage = () => {
  return (
    <>
      <Head>
        <title>Confirmação de Envio | ConsultPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container>
        <S.Content>
          <S.ContOne>
            <h1>
              Formulário preenchido
              <br />
              com sucesso!
            </h1>
          </S.ContOne>
          <S.ContTwo>{/* imagem de medico */}</S.ContTwo>
        </S.Content>
      </S.Container>
    </>
  );
};

export default ShippingConfirmation;
