import * as S from '../../styles/NutritionalPageStyles/styles';
import { NextPage } from 'next';
import Head from 'next/head';
import { NutritionalStep } from '../../components/HealthStep/NutritionalStep';
import { BookIcon, NoteIcon } from '@primer/octicons-react';

const NutritionalPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ficha de Saúde | ConsultPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.View>
        <S.Container>
          <header>
            <h1>Ficha da(o) Paciente</h1>
            <BookIcon size={40} className="image-header" />
          </header>

          <main>
            <NutritionalStep />
          </main>
        </S.Container>
      </S.View>
    </>
  );
};

export default NutritionalPage;
